### ISSUE TITLE
Install conjure-up

### ISSUE THREAD

**Issue by kurron** [kurron/ansible-role-operations#6]
Add [conjure-up](http://conjure-up.io/) to make installation of Kubernetes, Kafka, and other large systems easier.

**Comment by alirezasabeti** [comment]
Hi 

I have this log which is generated during the install OpenstackLXD. please help 



2021-07-27 12:14:06,534 [WARNING] conjure-up/openstack-novalxd - urllib3.connectionpool: connectionpool.py:277 - Connection pool is full, discarding connection: api.jujucharms.com
2021-07-27 12:14:11,341 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Configure Application
2021-07-27 12:14:12,018 [INFO] conjure-up/openstack-novalxd - applicationconfigure.py:87 - Hiding options not in the whitelist: ['auth-supported', 'ceph-cluster-network', 'ceph-public-network', 'config-flags', 'customize-failure-domain', 'default-rbd-features', 'expected-osd-count', 'harden', 'key', 'loglevel', 'monitor-count', 'monitor-hosts', 'monitor-secret', 'nagios_context', 'nagios_degraded_thresh', 'nagios_ignore_nodeepscub', 'nagios_misplaced_thresh', 'nagios_recovery_rate', 'nagios_servicegroups', 'no-bootstrap', 'pgs-per-osd', 'prefer-ipv6', 'source', 'sysctl', 'use-direct-io', 'use-syslog']
2021-07-27 12:15:26,551 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Configure Applications
2021-07-27 12:15:36,192 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:17 - Showing screen: Bootstrapping Controller
2021-07-27 12:15:36,308 [INFO] conjure-up/openstack-novalxd - common.py:74 - Bootstrapping Juju controller...
2021-07-27 12:15:36,309 [DEBUG] conjure-up/openstack-novalxd - telemetry.py:32 - Juju Bootstrap: Started
2021-07-27 12:15:36,310 [DEBUG] conjure-up/openstack-novalxd - juju.py:213 - Bootstrapping to set region: {}
2021-07-27 12:15:36,312 [DEBUG] conjure-up/openstack-novalxd - juju.py:252 - bootstrap cmd: ['/snap/bin/juju', 'bootstrap', 'localhost/localhost', 'conjure-up-localhost-d80', '--default-model', 'conjure-openstack-novalx-29f', '--config', 'image-stream=daily', '--credential', 'localhost']
2021-07-27 12:15:36,322 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Awaiting Bootstrapped at conjureup/controllers/juju/bootstrap/gui.py:43






2021-07-27 12:35:54,790 [ERROR] conjure-up/openstack-novalxd - common.py:60 - Error bootstrapping controller: ['Creating Juju controller "conjure-up-localhost-d80" on localhost/localhost', 'Looking for packaged Juju agent version 2.8.1 for amd64', 'To configure your system to better support LXD containers, please see: https://github.com/lxc/lxd/blob/master/doc/production-setup.md', 'Launching controller instance(s) on localhost/localhost...', ' - acquiring LXD image', '                      ', ' - Creating container', ' - Container started', '                      ', ' - juju-75c4cd-0 (arch=amd64)          ', 'Installing Juju agent on bootstrap instance', 'Fetching Juju Dashboard 0.8.0', 'Waiting for address', 'Attempting to connect to 20.20.20.2:22', 'ERROR failed to bootstrap model: waited for 20m0s without being able to connect: ssh: symbol lookup error: /snap/core18/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_vfork, version GLIBC_PRIVATE']
2021-07-27 12:35:54,792 [DEBUG] conjure-up/openstack-novalxd - events.py:52 - Setting Error at conjureup/events.py:149
2021-07-27 12:35:54,806 [ERROR] conjure-up/openstack-novalxd - events.py:161 - Unhandled exception in <Task finished coro=<BaseBootstrapController.run() done, defined at /snap/conjure-up/1062/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py:15> exception=BootstrapError('Unable to bootstrap (cloud type: localhost)',)>
Traceback (most recent call last):
  File "/snap/conjure-up/1062/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 21, in run
    await self.do_bootstrap()
  File "/snap/conjure-up/1062/lib/python3.6/site-packages/conjureup/controllers/juju/bootstrap/common.py", line 65, in do_bootstrap
    app.provider.cloud_type))
conjureup.errors.BootstrapError: Unable to bootstrap (cloud type: localhost)
2021-07-27 12:35:54,818 [DEBUG] conjure-up/openstack-novalxd - __init__.py:27 - Showing dialog for exception: Unable to bootstrap (cloud type: localhost)

**Comment by kurron** [comment]
I'm sorry but I am not sure what might be causing the problem. I usually
ensure all versions of tools and libraries are up to date when I run into
such a problem.

Ron
